openapi: 3.0.3
info:
    title: MCP server to serve as a RAG pipeline by allowing an LLM to write and read in a vector DB. API
    description: A simple API for MCP server to serve as a RAG pipeline by allowing an LLM to write and read in a vector DB.
    version: "1.0"
servers:
    - url: http://localhost:80
      description: MCP server to serve as a RAG pipeline by allowing an LLM to write and read in a vector DB. server
paths:
    /checks/health:
        get:
            tags:
                - health
            summary: getHealth health
            description: Returns OK if the service is healthy
            operationId: health#getHealth
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HealthCheckResponse'
                            example:
                                healthy: true
                                message: MCP RAG Vector API is healthy
components:
    schemas:
        HealthCheckResponse:
            type: object
            properties:
                healthy:
                    type: boolean
                    description: health or not
                    example: true
                message:
                    type: string
                    description: health message
                    example: MCP RAG Vector API is healthy
            description: Response containing health check status
            example:
                healthy: true
                message: MCP RAG Vector API is healthy
            required:
                - healthy
tags:
    - name: health
      description: Health check service
